### ISSUE TITLE
[SkullUtils] - Property Value error

### ISSUE THREAD

**Issue by IDavidML** [CryptoMorin/XSeries#230]
With the recent changes in SkullUtils, it give me an error with the new method:
![image](https://github.com/CryptoMorin/XSeries/assets/16390206/08525c41-4112-4ac0-9af3-837119bed5b1)

Supposedly it should only be called in versions 1.20.2 or later, but I'm on 1.19.4 and it runs anyway.
![image](https://github.com/CryptoMorin/XSeries/assets/16390206/59931abd-e67c-4759-ac8b-e10cba80eb8a)

**Comment by CryptoMorin** [comment]
Yeah my bad. I don't know why i put 12 instead of 20 there.

**Comment by darbyjack** [comment]
Started having reports of this as well. Is this planned to be fixed for the 9.7.0 release?

**Comment by CryptoMorin** [comment]
Yep, I'm just finalizing 1.20.2

**Comment by CryptoMorin** [comment]
Fixed in v9.6.1

**Comment by timderspieler** [comment]
@CryptoMorin thank you for the fix, but its still not working on 1.19.4 (Paper):

![grafik](https://github.com/CryptoMorin/XSeries/assets/19387835/9a7bc7f7-8769-4e6d-b4d1-3706136c8b2b)

I am using the SkullUtils.applySkin method combine with a Base64 encoded skin.

On 1.20.2, everything still works fine.

**Comment by timderspieler** [comment]
Any news on this? :)

**Comment by CryptoMorin** [comment]
Fixed in v9.7.0 sorry for the delay.
